In [1]:
import pandas as pd
import numpy as np

# First, we will load in the datasets we are using.

In [2]:
# Business data with location, name, id, number of reviews, Yelp rating, categories, hours, and is open
bus_df = pd.read_json('yelp_academic_dataset_business.json', lines=True)
bus_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'..."
1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",None
2,XNoUzKckATkOD1hP6vghZg,Felinus,3554 Rue Notre-Dame O,Montreal,QC,H4C 1P4,45.479984,-73.580070,5.0,5,1,None,"Pets, Pet Services, Pet Groomers",None
3,6OAZjbxqM5ol29BuHsil3w,Nevada House of Hose,1015 Sharp Cir,North Las Vegas,NV,89030,36.219728,-115.127725,2.5,3,0,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Hardware Stores, Home Services, Building Suppl...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ..."
4,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726648,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209388,9Q0fPWAjUweoFDk0kafuzQ,Nishi Sushi,9750 Weston Road,Vaughan,ON,L4H 2P2,43.838555,-79.559823,4.0,5,0,"{'Ambience': '{'romantic': False, 'intimate': ...","Japanese, Sushi Bars, Restaurants","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209389,PotiAhtDMYMNsJCzV0oLAw,Walmart,3240 Wilkinson Blvd,Charlotte,NC,28208,35.226307,-80.893539,2.0,13,0,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","Department Stores, Food, Mobile Phones, Fashio...",None
209390,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209391,RSSIsgO00OuWQTRoITacpA,Indian Trail Dog Training,,Indian Trail,NC,28079,35.101965,-80.599385,5.0,3,1,None,"Pet Services, Pet Training, Pets","{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '..."
209392,tOcYmewXFhQeZh3V42ymwg,Kudlow Ye,"21 St Clair Avenue E, Suite 401",Toronto,ON,M4T 1L9,43.688214,-79.392756,5.0,3,1,None,"Tax Services, Professional Services, Accountan...","{'Monday': '9:0-18:0', 'Tuesday': '9:0-18:0', ..."

In [3]:
# Not necessary
check_df = pd.read_json('yelp_academic_dataset_checkin.json', lines=True)
check_df

,business_id,date
0,--1UhMGODdWsrMastO9DZw,"2016-04-26 19:49:16, 2016-08-30 18:36:57, 2016..."
1,--6MefnULPED_I942VcFNA,"2011-06-04 18:22:23, 2011-07-23 23:51:33, 2012..."
2,--7zmmkVg-IMGaXbuVd0SQ,"2014-12-29 19:25:50, 2015-01-17 01:49:14, 2015..."
3,--8LPVSo5i0Oo61X01sV9A,2016-07-08 16:43:30
4,--9QQLMTbFzLJ_oT-ON3Xw,"2010-06-26 17:39:07, 2010-08-01 20:06:21, 2010..."
...,...,...
175182,zzvlwkcNR1CCqOPXwuvz2A,"2017-05-06 20:05:15, 2017-05-12 22:37:03, 2017..."
175183,zzwaS0xn1MVEPEf0hNLjew,"2010-02-16 02:09:56, 2010-07-05 05:40:48, 2010..."
175184,zzwhN7x37nyjP0ZM8oiHmw,"2016-03-06 13:27:02, 2016-03-09 00:41:53, 2016..."
175185,zzwicjPC9g246MK2M1ZFBA,"2012-09-22 00:26:15, 2012-09-23 20:12:00, 2012..."
175186,zzzaIBwimxVej4tY6qFOUQ,"2012-10-12 16:26:35, 2012-10-19 19:31:14, 2012..."

In [4]:
#Population data
pop_df = pd.read_csv('pop-by-zip-code.csv',dtype={'zip_code':'str'})
pop_df

,zip_code,y-2016,y-2015,y-2014,y-2013,y-2012,y-2011,y-2010,aggregate
0,00601,17800,17982,18088,18450,18544,18533,18570,127967
1,00602,39716,40260,40859,41302,41640,41930,41520,287227
2,00603,51565,52408,53162,53683,54540,54475,54689,374522
3,00606,6320,6331,6415,6591,6593,6386,6615,45251
4,00610,27976,28328,28805,28963,29141,29111,29016,201340
...,...,...,...,...,...,...,...,...,...
33115,99923,0,13,12,81,77,116,87,386
33116,99925,908,826,728,668,673,689,819,5311
33117,99926,1667,1711,1622,1630,1624,1488,1460,11202
33118,99927,81,123,131,111,75,67,94,682
33119,99929,2385,2365,2354,2341,2361,2321,2338,16465

# Now, we will prepare the data for our project.

In [5]:
# Clean data to remove all Canadian locations. We'll be using U.S. locations for this project.
# For this, we will get the dataframe to only have cases with a 5-digit postal code.
bus_df = bus_df[bus_df['postal_code'].str.contains(r'^\d{5}$')]
bus_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'..."
1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",None
3,6OAZjbxqM5ol29BuHsil3w,Nevada House of Hose,1015 Sharp Cir,North Las Vegas,NV,89030,36.219728,-115.127725,2.5,3,0,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Hardware Stores, Home Services, Building Suppl...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ..."
4,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726648,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '..."
5,cKyLV5oWZJ2NudWgqs8VZw,Oasis Auto Center - Gilbert,"1720 W Elliot Rd, Ste 105",Gilbert,AZ,85233,33.350399,-111.827142,4.5,38,1,{'BusinessAcceptsCreditCards': 'True'},"Auto Repair, Automotive, Oil Change Stations, ...","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209385,hskVqZCPqy-omm9CHi44xQ,Domino's,"6420 Rea Rd, Suite B1",Charlotte,NC,28226,35.078538,-80.818358,2.0,16,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Restaurants, Pizza, Sandwiches, Fast Food, Chi...","{'Monday': '10:30-0:0', 'Tuesday': '10:30-0:0'..."
209386,JjcJVqhZXhP4tvOhg3fnag,Water Heater Pros,,Las Vegas,NV,89120,36.076977,-115.244794,5.0,217,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Contractors, Local Services, Appliances & Repa...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '..."
209389,PotiAhtDMYMNsJCzV0oLAw,Walmart,3240 Wilkinson Blvd,Charlotte,NC,28208,35.226307,-80.893539,2.0,13,0,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","Department Stores, Food, Mobile Phones, Fashio...",None
209390,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'..."
209391,RSSIsgO00OuWQTRoITacpA,Indian Trail Dog Training,,Indian Trail,NC,28079,35.101965,-80.599385,5.0,3,1,None,"Pet Services, Pet Training, Pets","{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '..."

## We need to find out which names need to be standardized.

In [6]:
# We will select the top 10 fast food chains and some extras for our analysis. But first, let's explore our dataset to
# make sure we're getting the way the names are inputted correctly. For example, Domino's Pizza is listed as just
# Domino's in this dataset.
mcd = bus_df[bus_df['name'].str.contains("McDonald")]
starb = bus_df[bus_df['name'].str.contains("Starbucks")]

#We notice that with Subway, some are called Subway Restaurants and some are just Subway. We will standardize this.
sub = bus_df[bus_df['name'].str.contains("Subway")]

bk = bus_df[bus_df['name'].str.contains("Burger King")]
tb = bus_df[bus_df['name'].str.contains("Taco Bell")]
wendys = bus_df[bus_df['name'].str.contains("Wendy")]

# Dunkin' also needs to be standardized as some are Dunkin',some are Dunkin' Donuts, some are with Baskin-Robbins.
dunkin = bus_df[bus_df['name'].str.contains("Dunkin")]

# Chick-fil-A needs to be standardized.
cfa = bus_df[bus_df['name'].str.contains("Chick-")]

# Some Domino's are just Domino's while some are Domino's Pizza. Needs to be standardized.
domino = bus_df[bus_df['name'].str.contains("Domino")]

pizza_hut = bus_df[bus_df['name'].str.contains("Pizza Hut")]

In [7]:
# Just for reference, this is what Dunkin' entries looked like.
bus_df[bus_df['name'].str.contains("Dunkin")]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
340,HccqNuvwDCrnAAM5e5lQ_w,Dunkin',4125 S Eastern Ave,Las Vegas,NV,89119,36.113742,-115.119507,2.5,76,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Coffee & Tea, Donuts, Food, Bakeries","{'Monday': '5:0-18:0', 'Tuesday': '5:0-18:0', ..."
533,rljaZWpdhJfrWAPT6kYb7g,Dunkin' Donuts/Baskin-Robbins,21015 Lorain Rd,Fairview Park,OH,44126,41.445915,-81.853363,3.0,15,1,"{'OutdoorSeating': 'True', 'BusinessParking': ...","Ice Cream & Frozen Yogurt, Coffee & Tea, Donut...",None
785,QZ-BhQotj-mSpTyse35udA,Dunkin',10240 N 90th St,Scottsdale,AZ,85258,33.579467,-111.886979,2.5,61,1,"{'BusinessAcceptsCreditCards': 'True', 'WiFi':...","Donuts, Food, Coffee & Tea","{'Monday': '4:0-21:0', 'Tuesday': '4:0-21:0', ..."
1053,uJIIgBmcIn-Ye-anrqK0DQ,Dunkin',1302 N. Prospect Ave,Champaign,IL,61820,40.128653,-88.257411,2.0,18,1,"{'RestaurantsPriceRange2': '1', 'OutdoorSeatin...","Donuts, Food, Coffee & Tea","{'Monday': '5:0-19:0', 'Tuesday': '5:0-19:0', ..."
3480,rd9DTyWkLAUr1z189DMj5w,Dunkin',5029 Beatties Ford Rd,Charlotte,NC,28216,35.304564,-80.858557,2.0,15,1,"{'BikeParking': 'True', 'BusinessParking': '{'...","Coffee & Tea, Donuts, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198294,r3kFRJuy7CTxamZycndqGw,Dunkin',"7430 Las Vegas Blvd, Ste 100",Las Vegas,NV,89123,36.054565,-115.171491,3.0,212,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Donuts, Coffee & Tea, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
200523,92UwiPi_dOQfCP9dxhOeQQ,Dunkin',6751 E. Wilkinson Blvd,Belmont,NC,28012,35.252260,-81.029012,2.5,18,1,"{'OutdoorSeating': 'False', 'BusinessParking':...","Food, Coffee & Tea, Donuts","{'Monday': '5:0-22:0', 'Tuesday': '5:0-22:0', ..."
203264,50tjBMTlIbFBxjTRXAVZHQ,Dunkin',"6935 N Durango Dr, Ste 150",Las Vegas,NV,89149,36.285821,-115.288547,2.0,132,1,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Coffee & Tea, Bagels, Donuts, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
204663,ylLChdh7Oyx3SW8SxOTlbA,Dunkin' Donuts,411 Smithfield St,Pittsburgh,PA,15222,40.439093,-79.999581,4.5,3,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Donuts, Food, Coffee & Tea","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
207689,wbVRLmGpJITCxDD20ceHWw,Dunkin',344 Rodi Rd,Penn Hills,PA,15235,40.458264,-79.823765,2.0,21,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Food, Coffee & Tea, Donuts, Restaurants","{'Monday': '5:0-22:0', 'Tuesday': '5:0-22:0', ..."

In [8]:
# Now, it's time to standardize these.

def standardize_restaurant(string):
    temp = string.lower()
    if "mcdonald" in temp:
        output = "McDonald's"
    elif "starbucks" in temp:
        output = "Starbucks"
    elif "subway" in temp:
        output = "Subway"
    elif "burger king" in temp:
        output = "Burger King"
    elif "taco bell" in temp:
        output = "Taco Bell"
    elif "wendy" in temp:
        output = "Wendy's"
    elif "dunkin" in temp:
        output = "Dunkin'"
    elif "chick-" in temp:
        output = "Chick-fil-A"
    elif "domino" in temp:
        output = "Domino's"
    elif "pizza hut" in temp:
        output = "Pizza Hut"
    else:
        output = string
    return output

In [9]:
bus_df['name'] = bus_df['name'].apply(standardize_restaurant)

/Users/rakesh/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [10]:
# Now let's see how this worked on Domino's.
bus_df[bus_df['name'].str.contains("Dunkin")]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
340,HccqNuvwDCrnAAM5e5lQ_w,Dunkin',4125 S Eastern Ave,Las Vegas,NV,89119,36.113742,-115.119507,2.5,76,1,"{'RestaurantsTakeOut': 'True', 'RestaurantsDel...","Coffee & Tea, Donuts, Food, Bakeries","{'Monday': '5:0-18:0', 'Tuesday': '5:0-18:0', ..."
533,rljaZWpdhJfrWAPT6kYb7g,Dunkin',21015 Lorain Rd,Fairview Park,OH,44126,41.445915,-81.853363,3.0,15,1,"{'OutdoorSeating': 'True', 'BusinessParking': ...","Ice Cream & Frozen Yogurt, Coffee & Tea, Donut...",None
785,QZ-BhQotj-mSpTyse35udA,Dunkin',10240 N 90th St,Scottsdale,AZ,85258,33.579467,-111.886979,2.5,61,1,"{'BusinessAcceptsCreditCards': 'True', 'WiFi':...","Donuts, Food, Coffee & Tea","{'Monday': '4:0-21:0', 'Tuesday': '4:0-21:0', ..."
1053,uJIIgBmcIn-Ye-anrqK0DQ,Dunkin',1302 N. Prospect Ave,Champaign,IL,61820,40.128653,-88.257411,2.0,18,1,"{'RestaurantsPriceRange2': '1', 'OutdoorSeatin...","Donuts, Food, Coffee & Tea","{'Monday': '5:0-19:0', 'Tuesday': '5:0-19:0', ..."
3480,rd9DTyWkLAUr1z189DMj5w,Dunkin',5029 Beatties Ford Rd,Charlotte,NC,28216,35.304564,-80.858557,2.0,15,1,"{'BikeParking': 'True', 'BusinessParking': '{'...","Coffee & Tea, Donuts, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198294,r3kFRJuy7CTxamZycndqGw,Dunkin',"7430 Las Vegas Blvd, Ste 100",Las Vegas,NV,89123,36.054565,-115.171491,3.0,212,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Donuts, Coffee & Tea, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
200523,92UwiPi_dOQfCP9dxhOeQQ,Dunkin',6751 E. Wilkinson Blvd,Belmont,NC,28012,35.252260,-81.029012,2.5,18,1,"{'OutdoorSeating': 'False', 'BusinessParking':...","Food, Coffee & Tea, Donuts","{'Monday': '5:0-22:0', 'Tuesday': '5:0-22:0', ..."
203264,50tjBMTlIbFBxjTRXAVZHQ,Dunkin',"6935 N Durango Dr, Ste 150",Las Vegas,NV,89149,36.285821,-115.288547,2.0,132,1,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Coffee & Tea, Bagels, Donuts, Food","{'Monday': '5:0-21:0', 'Tuesday': '5:0-21:0', ..."
204663,ylLChdh7Oyx3SW8SxOTlbA,Dunkin',411 Smithfield St,Pittsburgh,PA,15222,40.439093,-79.999581,4.5,3,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Donuts, Food, Coffee & Tea","{'Monday': '6:0-19:0', 'Tuesday': '6:0-19:0', ..."
207689,wbVRLmGpJITCxDD20ceHWw,Dunkin',344 Rodi Rd,Penn Hills,PA,15235,40.458264,-79.823765,2.0,21,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Food, Coffee & Tea, Donuts, Restaurants","{'Monday': '5:0-22:0', 'Tuesday': '5:0-22:0', ..."

In [16]:
# Now, let's merge the population data to include an extra parameter that could have an impact on our project.
# For our case, we will use the most recent population data we have.
new_pop_df = pop_df[['zip_code','y-2016']]
bus_df = bus_df.rename(columns={"postal_code":"zip_code"})
df = bus_df.merge(new_pop_df, how='left', on='zip_code')
df = df.rename(columns={"y-2016":"population"})
df

,business_id,name,address,city,state,zip_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours,population
0,f9NumwFMBDn751xgFiRbNA,The Range At Lake Norman,10913 Bailey Rd,Cornelius,NC,28031,35.462724,-80.852612,3.5,36,1,"{'BusinessAcceptsCreditCards': 'True', 'BikePa...","Active Life, Gun/Rifle Ranges, Guns & Ammo, Sh...","{'Monday': '10:0-18:0', 'Tuesday': '11:0-20:0'...",26686.0
1,Yzvjg0SayhoZgCljUJRF9Q,"Carlos Santo, NMD","8880 E Via Linda, Ste 107",Scottsdale,AZ,85258,33.569404,-111.890264,5.0,4,1,"{'GoodForKids': 'True', 'ByAppointmentOnly': '...","Health & Medical, Fitness & Instruction, Yoga,...",None,23933.0
2,6OAZjbxqM5ol29BuHsil3w,Nevada House of Hose,1015 Sharp Cir,North Las Vegas,NV,89030,36.219728,-115.127725,2.5,3,0,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Hardware Stores, Home Services, Building Suppl...","{'Monday': '7:0-16:0', 'Tuesday': '7:0-16:0', ...",47895.0
3,51M2Kk903DFYI6gnB5I6SQ,USE MY GUY SERVICES LLC,4827 E Downing Cir,Mesa,AZ,85205,33.428065,-111.726648,4.5,26,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Home Services, Plumbing, Electricians, Handyma...","{'Monday': '0:0-0:0', 'Tuesday': '9:0-16:0', '...",41376.0
4,cKyLV5oWZJ2NudWgqs8VZw,Oasis Auto Center - Gilbert,"1720 W Elliot Rd, Ste 105",Gilbert,AZ,85233,33.350399,-111.827142,4.5,38,1,{'BusinessAcceptsCreditCards': 'True'},"Auto Repair, Automotive, Oil Change Stations, ...","{'Monday': '7:0-18:0', 'Tuesday': '7:0-18:0', ...",35828.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153574,hskVqZCPqy-omm9CHi44xQ,Domino's,"6420 Rea Rd, Suite B1",Charlotte,NC,28226,35.078538,-80.818358,2.0,16,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","Restaurants, Pizza, Sandwiches, Fast Food, Chi...","{'Monday': '10:30-0:0', 'Tuesday': '10:30-0:0'...",39052.0
153575,JjcJVqhZXhP4tvOhg3fnag,Water Heater Pros,,Las Vegas,NV,89120,36.076977,-115.244794,5.0,217,1,"{'BusinessAcceptsCreditCards': 'True', 'ByAppo...","Contractors, Local Services, Appliances & Repa...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-17:0', '...",24830.0
153576,PotiAhtDMYMNsJCzV0oLAw,Walmart,3240 Wilkinson Blvd,Charlotte,NC,28208,35.226307,-80.893539,2.0,13,0,"{'RestaurantsPriceRange2': '1', 'BusinessParki...","Department Stores, Food, Mobile Phones, Fashio...",None,36328.0
153577,SYa2j1boLF8DcGVOYfHPcA,Five Guys,7014-590 E Camelback Rd,Scottsdale,AZ,85251,33.504062,-111.929431,3.5,97,1,"{'BusinessAcceptsCreditCards': 'True', 'Restau...","American (New), Food, Burgers, Restaurants, Fa...","{'Monday': '11:0-22:0', 'Tuesday': '11:0-22:0'...",39867.0
153578,RSSIsgO00OuWQTRoITacpA,Indian Trail Dog Training,,Indian Trail,NC,28079,35.101965,-80.599385,5.0,3,1,None,"Pet Services, Pet Training, Pets","{'Monday': '0:0-0:0', 'Tuesday': '7:0-19:0', '...",34282.0

In [ ]:
# Now let's reduce this dataframe to just the restaurants chains we're examining.